Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,9 +35,6 @@ jobs:
           path: ~/.sonar/cache
           key: ${{ runner.os }}-sonar
           restore-keys: ${{ runner.os }}-sonar
-      # Installation de jq
-      - name: Install jq
-        run: sudo apt-get install jq
       - name: Vérifie si le porjet sonar cloud exist, sinon on le créé
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -50,6 +47,10 @@ jobs:
           # Essayez d'extraire la valeur du champ total
           total=$(echo "$response" | jq '.paging.total')
 
+          if [ $? -ne 0 ]; then
+              echo "Failed to parse the total from response. Response was: $response"
+              exit 1
+          fi
           # Affichez la valeur de total pour le débogage
           echo "Total: lala"
 
